AA-2 Edit company init
Lavina-Tech-LLC/fast-food-monorepo pull request #16
Opened 2022-11-16 13:46 UTC by theninjacoder-uz

2022-11-16 13:55 UTC, khdoba2000 requested changes

2022-11-16 13:55 UTC, khdoba2000 commented on src/config_service/storage/postgres/config.go
> +	err := r.db.GetContext(ctx, exist, `SELECT true FROM companies WHERE id=$1`, req.Id)
why you are checking like this. You can get not found info from Update statement too.

2022-11-16 14:01 UTC, theninjacoder-uz commented on src/config_service/storage/postgres/config.go
> +	err := r.db.GetContext(ctx, exist, `SELECT true FROM companies WHERE id=$1`, req.Id)
Sunbula said that ExecContext(`Update ...`) not return error if row not found

2022-11-17 06:36 UTC, khdoba2000 requested changes

2022-11-17 06:36 UTC, khdoba2000 commented on src/config_service/service/company.go
> +			return &pb.Empty{}, status.Error(codes.NotFound, err.Error())
for pb.Empty return nil instead

2022-11-17 06:36 UTC, khdoba2000 commented on src/config_service/pkg/mappers/mapper.go
> +		return &entity.Company{}, nil
You will lose the error of validating req.ID here. Should be "return nil, err"

2022-11-17 06:36 UTC, khdoba2000 commented on src/config_service/service/company.go
> +			return &pb.Empty{}, status.Error(codes.NotFound, err.Error())
for all pointer expected returns you should return nil if any error arises during operations.

2022-11-17 06:36 UTC, khdoba2000 commented on src/config_service/storage/postgres/company.go
> +	if err := tx.QueryRowContext(
I said earlier to use Execute for insert update queries.

2022-11-17 06:36 UTC, khdoba2000 commented on src/config_service/storage/postgres/company.go
> +		`WITH rows AS (
you still did not get my point, remove with rows as. just do "UPDATE ******** RETURNING *" this query returns rows and error(if any).  and then You can get length of rows in **go code** not is postgres.

2022-11-17 06:36 UTC, khdoba2000 commented on src/config_service/storage/postgres/company.go
> +	).Scan(count); err != nil {
you will not need to scan after above changes.

2022-11-17 06:36 UTC, khdoba2000 commented on src/config_service/storage/postgres/company.go
> +	if count != 1 {
check will be like that "if len(rows)==0"

2022-11-17 09:46 UTC, khdoba2000 commented on src/config_service/service/company.go
> +	return nil, nil
here the prev version was reasonable, there is concept that if function returns with some error it should return nil, 0, "" values for the expected result.

2022-11-17 09:52 UTC, khdoba2000 approved these changes

2022-11-17 09:52 UTC, merged